services:
  - type: web
    name: notes-manager
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: notes-db
    ipAllowList: []